### ISSUE TITLE
Call server processes not under supervision

### ISSUE THREAD

**Issue by schlagert** [kalta/nksip#39]
Hi,

I was just wondering why call processes are not showing up in the `nksip` supervision tree e.g. when using `observer`. After browsing the source I found out that `nksip_call_srv` processes are started unsupervised using `gen_server:start/3`. Is there any special reason for that?

If there is a reason for that (and I'm assuming there is), this could be worth mentioning in the otherwise great documentation. Besides not showing up in monitoring tools having unsupervised processes has the disadvantage that these processes will not be shutdown when the `nksip` application or the respective `sipapp` gets stopped.

Regards
Tobias

**Comment by kalta** [comment]
Hi,

I wrote that code long ago, and I don't really remember now why I didn't link to the supervisor, but I am sure I had a reason... 

I don't have time now to study it. I plan to go back to NkSIP for a big rewrite, integrating it into NetComposer, using maps, etc., in a few weeks.

**Comment by schlagert** [comment]
Ok, I can live with that for now :wink:
