### ISSUE TITLE
MAX_UDP

### ISSUE THREAD

**Issue by dzimi** [kalta/nksip#45]
Hi !

I have a question: why do you limit max udp message size in nksip_connection module ?
-define(MAX_UDP, 1500).

When we send SIP INVITE with big sdp nksip force to use tcp connection. Why? 
We've removed the limitation and the udp message was fragmented , which was expected situation due tu Ethernet MTU. It worked.

**Comment by kalta** [comment]
Hi,

From RFC3261 18.1.1:
"If a request is within 200 bytes of the path MTU, or if it is larger than 1300 bytes and the path MTU is unknown, the request MUST be sent using an RFC 2914 [36] congestion controlled transport protocol, such as TCP. If this causes a change in the transport protocol from the one indicated in the top Via, the value in the top Via MUST be changed. This prevents fragmentation of messages over UDP and provides congestion control for larger messages. However, implementations MUST be able to handle messages up to the maximum datagram packet size. For UDP, this size is 65,535 bytes, including IP and UDP headers."

What do you mean with "fragmented"? NkSIP should not be able to accept "fragmented" messages, if a incoming UDP does not have all the SIP first line and headers it will be rejected... It worked?
