### ISSUE TITLE
Update Cowboy to 1.0

### ISSUE THREAD

**Issue by essen** [kalta/nksip#47]
Hi, any plans to update Cowboy to 1.0? This would make nksip compatible as a dep with erlang.mk.

**Comment by kalta** [comment]
Yes, I`ll have a look as soon as possible.

**Comment by kalta** [comment]
Branch 0.5 is based on NkPACKET that uses Cowboy 1.0

**Comment by essen** [comment]
I confirm that the 0.5 branch works fine. Can you please ping here when the branch gets merged to master?

**Comment by kalta** [comment]
For sure

**Comment by kalta** [comment]
Hi, I forgot this thread. Master is already updated
