### ISSUE TITLE
Unable to connect to sip2sip

### ISSUE THREAD

**Issue by eshikafe** [kalta/nksip#51]
austin@aviela:~/nksip$ make shell
erl -config priv/app.config -args_file priv/vm.args
Erlang/OTP 18 [erts-7.0] [source] [64-bit] [async-threads:10] [kernel-poll:false]

Eshell V7.0  (abort with ^G)
(nksip_shell@127.0.0.1)1> 23:41:04.738 [notice] NkSIP v0.4.0 has started. Main IP is 10.0.2.15 (::1)

(nksip_shell@127.0.0.1)1> nksip:start(c1, nksip_sipapp, [], []).
{ok,abx7wd8}
(nksip_shell@127.0.0.1)2> nksip_uac:options(c1, "sip:sip2sip.info", []).
23:42:24.296 [notice] c1 (XKsSdLPICUojjGyzx8jLKdODjjk) error connecting to {81,23,228,150}:443 (tls): no_listening_transport
23:42:24.296 [notice] c1 (XKsSdLPICUojjGyzx8jLKdODjjk) error connecting to {81,23,228,129}:443 (tls): no_listening_transport
23:42:24.296 [notice] c1 (XKsSdLPICUojjGyzx8jLKdODjjk) error connecting to {85,17,186,7}:443 (tls): no_listening_transport
23:42:53.034 [warning] c1 (XKsSdLPICUojjGyzx8jLKdODjjk) error calling send_work_sync (send): {timeout,{gen_server,call,[nksip_router_12,{send_work_sync,abx7wd8,<<"XKsSdLPICUojjGyzx8jLKdODjjk">>,{send,'OPTIONS',"sip:sip2sip.info",[supported,allow,allow_event]},<0.43.0>},30000]}}
{error,timeout}
(nksip_shell@127.0.0.1)3>

**Comment by kalta** [comment]
Hi, you have at least two problems:

when connecting to sip2sip, it asks (using DNS) to use TLS, and you started nksip without any tls transports. You can start with nksip:start(c1, nksip_sipapp, [], [{transports, [{udp, all, 5060}, {pls, all, 5061}]}]) and works (for me).

Also, even without tls support, you will see those errors, but then it should switch to tcp and udp and work. Are you sure you have open internet connectivity?
