### ISSUE TITLE
Support tuple IP in URIs

### ISSUE THREAD

**Issue by chemeris** [kalta/nksip#54]
If you pass an #uri{} as a 'to'/'from'/'ruri' meta to nksip_uac functions, you get a cryptic error message like this one:
[error] gen_server <0.374.0> terminated with reason: bad argument in call to erlang:list_to_binary([<<>>,60,<<"sip">>,58,[<<"xxx">>,64],{172,31,0,18},[58,"5060"],<<>>,[],[],62,[[59,<<"tag">>,...]],...]) in nklib_unparse:header/1 line 89

The reason is that domain part of the URI is assumed to be a binary or a string and is used as is. Now I'm forced to use nklib_util:to_host/1 before passing the IP address to a sending function, while it looks like it's better to allow tuple typed IPs as an input and pass them through nklib_util:to_host/1 internally.

PS I'm using the current master branch.

**Comment by kalta** [comment]
Hi,

It could make sense, butit is not so easy. The #uri{} structure is used extensively in many projects, and the host part is supposed to be a binary. I would need to modify thousands of lines of code to supported tuples there.

**Comment by chemeris** [comment]
I see. May be putting this into the #uri{} documentation would be enough.
